declare module "module-api" {

    // Generated by https://quicktype.io

    export interface IModule {
        id: number;
        title: string;
        create: string;
        update: string;
        theme: string;
        mode: number;
    }
    export interface ISenario {
        id: string;
        name: string;
        mode: number;
        create: string;
        update: string;
        index: number;
    }


}