declare module "senario-data-api" {
    // Generated by https://quicktype.io

    export interface ISenarioData {
        modules: ISenarioModule[];
    }

    export interface ISenarioModule {
        theme: string;
        underuse?: bool;
        index: number;
        id: number;
        module: number;
        title: string;
    }

}